### ISSUE TITLE
"German" is not a valid "language" parameter

### ISSUE THREAD

**Issue by thomafe** [2Who/DHBW_BERTopic#9]
![image](https://user-images.githubusercontent.com/46815897/116872498-46ae0600-ac16-11eb-9e6e-17e0f964da72.png)
In the documentation from BERT it shows, that there are two different models. One is english, one multilangual. The language "german" is not available as a parameter! So the model trained by the code is propably using the enlish sentence transformer!

**Comment by steibern** [comment]
We take the language option => "multilingual". We will create a new model to see if there will be any differences! Thank you!

**Comment by 2Who** [comment]
A multilingual model was created and saved to the gdrive location specified in the kanban board.
